export const tripChoices = [
  { label: "Kathmandu", value: "kathmandu" },
  { label: "Pokhara", value: "pokhara" },
  { label: "Chitwan", value: "chitwan" },
  { label: "Lumbini", value: "lumbini" },
  { label: "Janakpur", value: "janakpur" },
  { label: "Biratnagar", value: "biratnagar" },
  { label: "Birgunj", value: "birgunj" },
  { label: "Dharan", value: "dharan" },
  { label: "Butwal", value: "butwal" },
  { label: "Hetauda", value: "hetauda" },
  { label: "Nepalgunj", value: "nepalgunj" },
  { label: "Dhangadhi", value: "dhangadhi" },
  { label: "Bharatpur", value: "bharatpur" },
  { label: "Itahari", value: "itahari" },
  { label: "Gaur", value: "gaur" },
  { label: "Tansen", value: "tansen" },
  { label: "Jomsom", value: "jomsom" },
  { label: "Namche Bazaar", value: "namche_bazaar" },
  { label: "Manang", value: "manang" },
  { label: "Lukla", value: "lukla" },
  { label: "Jaleswor", value: "jaleswor" },
  { label: "Mathayani", value: "mathayani" },
];
